# Generated by Django 6.1 on 2026-08-29 07:24

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=60)),
                ('age', models.IntegerField(validators=[django.core.validators.MinValueValidator(18), django.core.validators.MaxValueValidator(70)])),
                ('position', models.CharField(choices=[('AD', 'Administrator'), ('MG', 'Manager'), ('RP', 'Receptionist'), ('HK', 'Housekeeper'), ('LC', 'Line Cook'), ('MT', 'Maintenance Technician'), ('SO', 'Security Officer')], default='RP', max_length=2)),
                ('salary', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('phone', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('hire_date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Guest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=60)),
                ('age', models.IntegerField(validators=[django.core.validators.MinValueValidator(18)])),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=1)),
                ('country', models.CharField(choices=[('UZ', 'Uzbekistan'), ('KZ', 'Kazakhstan'), ('RU', 'Russia'), ('GB', 'United Kingdom'), ('AZ', 'Azerbaijan'), ('DE', 'Germany'), ('IT', 'Italy'), ('FR', 'France')], max_length=2)),
                ('city', models.CharField(max_length=50)),
                ('phone', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=100)),
                ('registered_date', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_number', models.IntegerField(validators=[django.core.validators.MinValueValidator(100), django.core.validators.MaxValueValidator(499)])),
                ('floor', models.CharField(choices=[('1F', 'First Floor'), ('2F', 'Second Floor'), ('3F', 'Third Floor'), ('4F', 'Fourth Floor')], max_length=2)),
                ('status', models.CharField(choices=[('VT', 'Vacant'), ('OC', 'Occupied'), ('DT', 'Dirty'), ('RS', 'Reserved'), ('MT', 'Maintenance')], default='VT', max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='RoomType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('BS', 'Basic'), ('CL', 'Classic'), ('PL', 'Plus'), ('FM', 'Family'), ('LX', 'Luxury')], default='BS', max_length=2)),
                ('description', models.TextField(validators=[django.core.validators.MinLengthValidator(50), django.core.validators.MaxLengthValidator(110)])),
                ('capacity', models.SmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(8)])),
                ('price_per_night', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('BR', 'Breakfast'), ('LN', 'Lunch'), ('CL', 'Cleaning'), ('LD', 'Laundry'), ('SH', 'Shuttle'), ('VT', 'Valet'), ('MS', 'Massage'), ('GM', 'Gym'), ('PR', 'Printing'), ('EV', 'Events')], max_length=2)),
                ('description', models.CharField(max_length=100)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('category', models.CharField(choices=[('DN', 'Dining'), ('HK', 'Housekeeping'), ('TR', 'Transport'), ('WL', 'Wellness'), ('BS', 'Business')], max_length=2)),
                ('available', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('check_in', models.DateField()),
                ('check_out', models.DateField()),
                ('guests_count', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)])),
                ('status', models.CharField(choices=[('CF', 'Confirmed'), ('PD', 'Pending'), ('CI', 'Checked-In'), ('CL', 'Cancelled'), ('NS', 'No-Show')], default='PD', max_length=2)),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('employee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Database.employee')),
                ('guest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='Database.guest')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='Database.room')),
            ],
        ),
        migrations.AddField(
            model_name='room',
            name='room_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rooms', to='Database.roomtype'),
        ),
        migrations.CreateModel(
            name='BookingService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)])),
                ('requested_at', models.DateTimeField(auto_now_add=True)),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='services', to='Database.booking')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Database.service')),
            ],
        ),
    ]
